[build]
  command = "npm run build" # Adjust if using a different build command
  publish = "dist" # Adjust if your build output directory is different
  
  [build.environment]
    # Configure secrets scanning to exclude build output and cached files
    SECRETS_SCAN_OMIT_PATHS = "dist/*,node_modules/*,.netlify/*,build/*,.next/*,.cache/*"

# Proxy API requests to portal.riftuni.com to avoid CORS issues
[[redirects]]
  from = "/api/proxy/*"
  to = "https://portal.riftuni.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/payment/generate-hash"
  to = "/.netlify/functions/generate-hash"
  status = 200
  force = true

# This redirect is last and will catch all other requests
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 