# Cloudflare Pages configuration
name = "ravana-iof"
compatibility_date = "2023-10-30"

# This is the key property needed for Pages
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

[build]
command = "npm run build:cloudflare"
output_directory = "dist"

[build.upload]
format = "directory" 