# Cloudflare Pages configuration
name = "ravana-iof"
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"

[build]
command = "npm run build"
output_directory = "dist"

[build.upload]
format = "directory" 